//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiskalnaKasaUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikal()
        {
            this.Dobavljanjes = new HashSet<Dobavljanje>();
        }
    
        public int SIF_ART { get; set; }
        public string Naziv { get; set; }
        public int Cena { get; set; }
        public int Min_Kolicina { get; set; }
        public int Kolicina { get; set; }
        public string BARCODE { get; set; }
        public int JedinicaMere_SIF_JEDMER { get; set; }
        public int Tarifa_SIF_TAR { get; set; }
        public int Grupa_SIF_GRP { get; set; }
    
        public virtual Grupa Grupa { get; set; }
        public virtual JedinicaMere JedinicaMere { get; set; }
        public virtual Tarifa Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dobavljanje> Dobavljanjes { get; set; }
    }
}
