//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiskalnaKasaUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dobavljanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dobavljanje()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int Kolicina { get; set; }
        public int Cena_Dobavljaca { get; set; }
        public int Marza_Procenat { get; set; }
        public int Marza_Vrednost { get; set; }
        public int Porez_Vrednost { get; set; }
        public int Maloprodajna_Vrednost { get; set; }
        public int Maloprodajna_Cena { get; set; }
        public int Artikal_SIF_ART { get; set; }
        public int Kalkulacija_SIF_KALK { get; set; }
    
        public virtual Artikal Artikal { get; set; }
        public virtual Kalkulacija Kalkulacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
    }
}
