//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiskalnaKasaUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalkulacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kalkulacija()
        {
            this.Dobavljanjes = new HashSet<Dobavljanje>();
        }
    
        public int SIF_KALK { get; set; }
        public System.DateTime Datum_Kalkulacije { get; set; }
        public int Partner_SIF_PART { get; set; }
        public int Radnik_SIF_RAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dobavljanje> Dobavljanjes { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Radnik Radnik { get; set; }
    }
}
