//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiskalnaKasaUI.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class FiskalnaKasaEntities : DbContext
    {
        public FiskalnaKasaEntities()
            : base("name=FiskalnaKasaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikal> Artikals { get; set; }
        public virtual DbSet<Dobavljanje> Dobavljanjes { get; set; }
        public virtual DbSet<Grupa> Grupas { get; set; }
        public virtual DbSet<JedinicaMere> JedinicaMeres { get; set; }
        public virtual DbSet<Kalkulacija> Kalkulacijas { get; set; }
        public virtual DbSet<Kasa> Kasas { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Tarifa> Tarifas { get; set; }
        public virtual DbSet<VrstaPlacanja> VrstaPlacanjas { get; set; }
        public virtual DbSet<Zaduzenje> Zaduzenjes { get; set; }
    }

    
}
