//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiskalnaKasaUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.VrstaPlacanjas = new HashSet<VrstaPlacanja>();
            this.Dobavljanjes = new HashSet<Dobavljanje>();
        }
    
        public int SIF_RAC { get; set; }
        public System.DateTime Datum_Izd { get; set; }
        public int Zaduzenje_Kasa_SIF_KAS { get; set; }
        public int Zaduzenje_Radnik_SIF_RAD { get; set; }
    
        public virtual Zaduzenje Zaduzenje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VrstaPlacanja> VrstaPlacanjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dobavljanje> Dobavljanjes { get; set; }
    }
}
